api/urls.py
from django.urls import path
from .views import Producto_Listado, Producto_Detalle, Cliente_Listado, \
                   Genera_Numero_factura_compra, Genera_Codigo_Producto
urlpatterns = [
    #Api Producto
    path('v1/productos/',Producto_Listado.as_view(),name='producto_listado'),
    path('v1/productos/<str:codigo>',Producto_Detalle.as_view(),name='producto_detalle'),
    path('v1/productos/generacodigo/',Genera_Codigo_Producto.as_view(),name='genera_codigo_producto'),

    #Api Cliente
    path('v1/clientes/',Cliente_Listado.as_view(),name='cliente_list'),

    #Api Compra
    path('v1/compra/generafactura/',Genera_Numero_factura_compra.as_view(),name='genera_numero_factura'),



]

app/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("",
         include(('bases.urls', 'bases'),
                 namespace='bases')),
    path("inventario/",
         include(('inventario.urls', 'inventario'),
                 namespace='inventario')),
    path("compra/",
         include(('compra.urls', 'compra'),
                 namespace='compra')),
    path("facturacion/",
         include(('facturacion.urls', 'facturacion'),
                 namespace='facturacion')),
    path("api/", include(('api.urls', 'api'),
                         namespace='api')),
    path('admin/', admin.site.urls),
]

bases/urls.py
from django.urls import path
from django.contrib.auth import views as autenticacion_vista
from .views import Inicio, Inicio_No_autorizado
urlpatterns = [
    path('', Inicio.as_view(), name='inicio'),
    path('login/', autenticacion_vista.LoginView.as_view(
        template_name='bases/login.html'), name='login'),
    path('salir/', autenticacion_vista.LogoutView.as_view(
        template_name='bases/login.html'), name='salir'),
    path('401/', Inicio_No_autorizado.as_view(), name="401"),
]

compra/urls.py
from django.urls import path
from .views import Proveedores_Vista,Proveedor_Agregar, Proveedor_Editar , Proveedor_Inactivar, \
                   Compra_Vista,Compras,Compra_Detalle_Eliminar

from .reporte import reporte_compras, imprimir_compra 

urlpatterns = [
    #proveedores
    path('proveedores/', Proveedores_Vista.as_view(),name='proveedores'),
    path('proveedores/agregar', Proveedor_Agregar.as_view(),name='proveedor_agregar'),
    path('proveedores/editar/<int:pk>', Proveedor_Editar.as_view(),name='proveedor_editar'),
    path('proveedores/inactivar/<int:id>', Proveedor_Inactivar,name='proveedor_inactivar'),
    #compras
    path('compras/',Compra_Vista.as_view(),name='compras'),
    path('compras/nuevas',Compras,name='compras_nuevas'),
    path('compras/editar/<int:compra_id>',Compras,name='compras_editar'),
    path('compras/<int:compra_id>/eliminar/<int:pk>',Compra_Detalle_Eliminar.as_view(),name='compras_eliminar'),

    #reporte
    path('compras/imprimir',reporte_compras, name='imprimir_todas'),
    path('compras/<int:compra_id>/imprimir', imprimir_compra,name="imprimir"),
]

facturacion/urls.py
from django.urls import path
from .views import Clientes_Vista, Cliente_Agregar, Cliente_Editar, cliente_Inactivar ,\
        Facturas_vista, facturas, Producto_vista, borrar_detalle_factura

from .reporte import imprimir_factura_recibo, imprimir_todas_factura

urlpatterns = [
    #cliente
    path('cliente/',Clientes_Vista.as_view(),name="clientes"),
    path('cliente/agregar',Cliente_Agregar.as_view(),name="cliente_agregar"),
    path('cliente/editar/<int:pk>',Cliente_Editar.as_view(),name="cliente_editar"),
    path('cliente/estado/<int:id>',cliente_Inactivar,name="cliente_inactivar"),
    #factura
    path('facturas/',Facturas_vista.as_view(),name="facturas_lista"),
    path('facturas/agregar',facturas,name="facturas_agregar"),
    path('facturas/editar/<int:id>',facturas, name="factura_editar"),
    path('facturas/borrar_detalle/<int:id>',borrar_detalle_factura, name="factura_borrar_detalle"),
    path('facturas/buscar-producto',Producto_vista.as_view(), name="factura_producto"),
    path('facturas/imprimir/<int:id>',imprimir_factura_recibo, name="factura_imprimir_una"),
    path('facturas/imprimir-todas/<str:fechainicio>/<str:fechafinal>',imprimir_todas_factura, name="factura_imprimir_todas"),


]

inventario/urls.py
from django.urls import path
from .views import Categoria_Vista, Categoria_Agregar, Categoria_Editar,Categoria_Inactivar,\
                   SubCategoria_Vista, SubCategoria_Agregar , SubCategoria_Editar,SubCategoria_Inactivar, \
                   Marca_Vista, Marca_Agregar,Marca_Editar, Marca_Inactivar, \
                   Unidad_Medida_Vista,Unidad_Medidad_Agregar, Unidad_Medida_Editar, Unidad_Medida_Inactivar, \
                   Producto_Vista, Producto_Agregar,Producto_Editar,Producto_Inactivar

urlpatterns = [
    #Categorias
    path('categorias/', Categoria_Vista.as_view(), name='categorias'),
    path('categorias/agregar/', Categoria_Agregar.as_view(), name='categoria_agregar'),
    path('categorias/editar/<int:pk>/', Categoria_Editar.as_view(), name='categoria_editar'),
    path('categorias/estado/<int:id>', Categoria_Inactivar, name='categoria_inactivar'),

    #SubCategorias
    path('subcategorias/', SubCategoria_Vista.as_view(), name='subcategorias'),
    path('subcategorias/agregar/', SubCategoria_Agregar.as_view(), name='subcategoria_agregar'),
    path('subcategorias/editar/<int:pk>/', SubCategoria_Editar.as_view(), name='subcategoria_editar'),
    path('subcategorias/estado/<int:id>', SubCategoria_Inactivar, name='subcategoria_inactivar'),

    #Marcas
    path('marcas/', Marca_Vista.as_view(), name='marcas'),
    path('marcas/agregar/', Marca_Agregar.as_view(), name='marca_agregar'),
    path('marcas/editar/<int:pk>', Marca_Editar.as_view(), name='marca_editar'),
    path('marcas/estado/<int:id>', Marca_Inactivar, name='marca_inactivar'),

    #Unidad de Medida
    path('unidamedidas/', Unidad_Medida_Vista.as_view(), name='unidadmedidas'),
    path('unidamedidas/agregar/', Unidad_Medidad_Agregar.as_view(), name='unidadmedida_agregar'),
    path('unidamedidas/editar/<int:pk>', Unidad_Medida_Editar.as_view(), name='unidadmedida_editar'),
    path('unidamedidas/estado/<int:id>',Unidad_Medida_Inactivar, name='unidadmedida_inactivar'),

    #productos
    path('productos/', Producto_Vista.as_view(), name='productos'),
    path('productos/agregar', Producto_Agregar.as_view(), name='productos_agregar'),
    path('productos/editar/<int:pk>', Producto_Editar.as_view(), name='productos_editar'),
    path('productos/estado/<int:id>', Producto_Inactivar, name='productos_inactivar'),

]

templates/app/base.html
{% load static %}
<!DOCTYPE html>
<html lang="es">
  <head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta
      name="viewport"
      content="width=device-width, initial-scale=1, shrink-to-fit=no"
    />
    <meta name="description" content="" />
    <meta name="author" content="" />

    <title>Sistema de Compra e Inventario</title>

    <!-- Custom fonts for this template-->
    <link
      href="{% static 'base/vendor/fontawesome-free/css/all.min.css' %}"
      rel="stylesheet"
      type="text/css"
    />
    <link
      href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i"
      rel="stylesheet"
    />

    <!-- Custom styles for this template-->
    <link href="{% static 'base/css/sb-admin-2.min.css' %}" rel="stylesheet" />
    <link href="{% static 'base/css/personalizado.css' %}" rel="stylesheet" />

    <link
      href="{% static 'base/vendor/datatables/dataTables.bootstrap4.min.css' %}"
      rel="stylesheet"
    />
    <link
      href="{% static 'base/vendor/sweetalert2/sweetalert2.min.css' %}"
      rel="stylesheet"
    />
    <link
      href="{% static 'base/vendor/datepicker/css/datetimepicker.min.css' %}"
      rel="stylesheet"
    />
    <link
      rel="stylesheet"
      href="https://unpkg.com/bootstrap-table@1.22.1/dist/bootstrap-table.min.css"
    />
    <link
      href="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.8/css/select2.min.css"
      rel="stylesheet"
    />
  </head>

  <body id="page-top" class="bg-gradient-primary">
    <!-- Page Wrapper -->
    <div id="wrapper">
      {% block barra_deslizante%}
      <!-- Sidebar -->
      <ul
        class="navbar-nav bg-gradient-primary sidebar sidebar-dark accordion"
        id="accordionSidebar"
      >
        <!-- Sidebar - Brand -->
        <a
          class="sidebar-brand d-flex align-items-center justify-content-center"
          href="{% url 'bases:inicio' %}"
        >
          <div class="sidebar-brand-icon rotate-n-15">
            <i class="fas fa-laugh-wink"></i>
          </div>
          <div class="sidebar-brand-text mx-3">FACTURACION</div>
        </a>

        <!-- Divider -->
        <hr class="sidebar-divider my-0" />

        <!-- Nav Item - Dashboard -->
        <li class="nav-item">
          <a class="nav-link" href="{% url 'bases:inicio' %}">
            <i class="fas fa-fw fa-tachometer-alt"></i>
            <span>Dashboard</span></a
          >
        </li>

        <!-- Divider -->
        <hr class="sidebar-divider" />

        <!-- Heading -->
        <div class="sidebar-heading">
          <!--titulo Menu-->
        </div>

        <!-- Nav Item - Pages Collapse Menu -->
        <li class="nav-item">
          <a
            class="nav-link collapsed"
            href="#"
            data-toggle="collapse"
            data-target="#collapseTwo"
            aria-expanded="true"
            aria-controls="collapseTwo"
          >
            <i class="fas fa-fw fa-cog"></i>
            <span>Catalogos</span>
          </a>
          <div
            id="collapseTwo"
            class="collapse"
            aria-labelledby="headingTwo"
            data-parent="#accordionSidebar"
          >
            <div class="bg-white py-2 collapse-inner rounded">
              <h6 class="collapse-header">Inventario:</h6>
              {% if perms.inventario.view_categoria %}
              <a class="collapse-item" href="{% url 'inventario:categorias' %}"
                >Categoria</a
              >
              {% endif %} {% if perms.inventario.view_subcategoria %}
              <a
                class="collapse-item"
                href="{% url 'inventario:subcategorias' %}"
                >Sub Categoria</a
              >
              {% endif %} {% if perms.inventario.view_marca %}
              <a class="collapse-item" href="{% url 'inventario:marcas' %}"
                >Marca</a
              >
              {% endif %} {% if perms.inventario.view_unidadmedida %}
              <a
                class="collapse-item"
                href="{% url 'inventario:unidadmedidas' %}"
                >Unidad de Medida</a
              >
              {% endif %} {% if perms.inventario.view_producto %}
              <a class="collapse-item" href="{% url 'inventario:productos' %}"
                >Productos</a
              >
              {% endif %}

              <h6 class="collapse-header">Compras:</h6>
              {% if perms.compra.view_proveedor %}
              <a class="collapse-item" href="{% url 'compra:proveedores' %}"
                >Proveedores</a
              >
              {% endif %}

              <h6 class="collapse-header">Facturacion:</h6>
              {% if perms.facturacion.view_cliente %}
              <a class="collapse-item" href="{% url 'facturacion:clientes' %}"
                >Cliente</a
              >
              {% endif %}
            </div>
          </div>
        </li>
        <li class="nav-item">
          <a
            class="nav-link collapsed"
            href="#"
            data-toggle="collapse"
            data-target="#collapseCompras"
            aria-expanded="true"
            aria-controls="collapseCompras"
          >
            <i class="fas fa-fw fa-truck"></i>
            <span>Movimientos</span>
          </a>
          <div
            id="collapseCompras"
            class="collapse"
            aria-labelledby="headingTwo"
            data-parent="#accordionSidebar"
          >
            <div class="bg-white py-2 collapse-inner rounded">
              <h6 class="collapse-header">Entradas</h6>
              <a class="collapse-item" href="{% url 'compra:compras' %}"
                >Compras</a
              >

              <h6 class="collapse-header">Salidas</h6>
              <a
                class="collapse-item"
                href="{% url 'facturacion:facturas_lista' %}"
                >Factura</a
              >
            </div>
          </div>
        </li>
        <!-- Divider -->
        <hr class="sidebar-divider d-none d-md-block" />

        <!-- Sidebar Toggler (Sidebar) -->
        <div class="text-center d-none d-md-inline">
          <button class="rounded-circle border-0" id="sidebarToggle"></button>
        </div>
      </ul>
      {% endblock barra_deslizante %}
      <div id="content-wrapper" class="d-flex flex-column">
        <div id="content">
          <!-- Topbar -->
          {% block barra_superior %}
          <nav
            class="navbar navbar-expand navbar-light bg-white topbar mb-4 static-top shadow"
          >
            <!-- Sidebar Toggle (Topbar) -->
            <button
              id="sidebarToggleTop"
              class="btn btn-link d-md-none rounded-circle mr-3"
            >
              <i class="fa fa-bars"></i>
            </button>

            <!-- Topbar Navbar -->
            <ul class="navbar-nav ml-auto">
              <!-- Nav Item - Alerts -->
              <li class="nav-item dropdown no-arrow mx-1"></li>

              <!-- Nav Item - Messages -->
              <li class="nav-item dropdown no-arrow mx-1"></li>

              <div class="topbar-divider d-none d-sm-block"></div>

              <!-- Nav Item - User Information -->
              <li class="nav-item dropdown no-arrow">
                <a
                  class="nav-link dropdown-toggle"
                  href="#"
                  id="userDropdown"
                  role="button"
                  data-toggle="dropdown"
                  aria-haspopup="true"
                  aria-expanded="false"
                >
                  <span class="mr-2 d-none d-lg-inline text-gray-600 small"
                    >{{user.username}}</span
                  >
                  <img
                    class="img-profile rounded-circle"
                    src="https://source.unsplash.com/QAB-WJcbgJk/60x60"
                  />
                </a>
                <!-- Dropdown - User Information -->
                <div
                  class="dropdown-menu dropdown-menu-right shadow animated--grow-in"
                  aria-labelledby="userDropdown"
                >
                  <a
                    class="dropdown-item"
                    href="#"
                    data-toggle="modal"
                    data-target="#logoutModal"
                  >
                    <i
                      class="fas fa-sign-out-alt fa-sm fa-fw mr-2 text-gray-400"
                    ></i>
                    Logout
                  </a>
                </div>
              </li>
            </ul>
          </nav>
          <!-- End of Topbar -->
          {% endblock barra_superior %}
          <!-- Begin Page Content -->
          {% block contenido %}
          <div class="container-fluid">
            <!-- Page Heading -->
            <h1 class="h3 mb-4 text-gray-800">Blank Page</h1>
          </div>
          {% endblock contenido %}
          <!-- /.container-fluid -->
        </div>
        <!-- End of Main Content -->

        <!-- Footer -->
        {% block pie_pagina %}
        <footer class="sticky-footer bg-white">
          <div class="container my-auto">
            <div class="copyright text-center my-auto">
              <span>Copyright &copy; Your Website 2019</span>
            </div>
          </div>
        </footer>
        <!-- End of Footer -->
        {% endblock pie_pagina %}
      </div>
      <!-- End of Content Wrapper -->
    </div>
    <!-- End of Page Wrapper -->
    {% block login %}{% endblock login %}
    <!-- Scroll to Top Button-->
    <a class="scroll-to-top rounded" href="#page-top">
      <i class="fas fa-angle-up"></i>
    </a>

    <!-- Logout Modal-->
    <div
      class="modal fade"
      id="logoutModal"
      tabindex="-1"
      role="dialog"
      aria-labelledby="exampleModalLabel"
      aria-hidden="true"
    >
      <div class="modal-dialog" role="document">
        <div class="modal-content">
          <div class="modal-header">
            <h5 class="modal-title" id="exampleModalLabel">Ready to Leave?</h5>
            <button
              class="close"
              type="button"
              data-dismiss="modal"
              aria-label="Close"
            >
              <span aria-hidden="true">×</span>
            </button>
          </div>
          <div class="modal-body">
            Seleccione "Cerrar sesión" a continuación si está listo para
            finalizar su sesión actual.
          </div>
          <div class="modal-footer">
            <button
              class="btn btn-secondary"
              type="button"
              data-dismiss="modal"
            >
              Cancel
            </button>
            <a class="btn btn-primary" href="{% url 'bases:salir' %}">Salir</a>
          </div>
        </div>
      </div>
    </div>

    <div class="modal fade" id="popup"></div>

    <script src="{% static 'base/vendor/jquery/jquery.min.js'%}"></script>
    <script src="{% static 'base/vendor/bootstrap/js/bootstrap.bundle.min.js'%}"></script>

    <script src="{% static 'base/vendor/jquery-easing/jquery.easing.min.js'%}"></script>

    <script src="{% static 'base/js/sb-admin-2.min.js'%}"></script>

    <script src="{% static 'ase/vendor/datatables/jquery.dataTables.min.js' %}"></script>
    <script src="{% static 'base/vendor/datatables/dataTables.bootstrap4.min.js'%}"></script>
    <script src="{% static 'base/vendor/sweetalert2/sweetalert2.min.js'%}"></script>
    <script src="{% static 'base/vendor/datepicker/js/datetimepicker.full.min.js'%}"></script>
    <script src="https://unpkg.com/bootstrap-table@1.22.1/dist/bootstrap-table.min.js"></script>
    <script src="https://unpkg.com/bootstrap-table@1.15.3/dist/bootstrap-table-locale-all.min.js"></script>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.8/js/select2.min.js"></script>
    <script src="{% static  'base/js/jquery.chained.min.js' %}"></script>
    <script src="{% static  'base/scripts/utilitario/utilitario.js' %}"></script>

    <script>

      {% if messages %}
        {% for mensaje in messages %}
         GestionarMensaje.MensajeInfo("Aviso","{{ mensaje }}");
        {% endfor %}
      {% endif %}
    </script>

    {% block js %}{% endblock js %}
  </body>
</html>