api/urls.py
from django.urls import path
from .views import Producto_Listado, Producto_Detalle, Cliente_Listado, \
                   Genera_Numero_factura_compra, Genera_Codigo_Producto
urlpatterns = [
    #Api Producto
    path('v1/productos/',Producto_Listado.as_view(),name='producto_listado'),
    path('v1/productos/<str:codigo>',Producto_Detalle.as_view(),name='producto_detalle'),
    path('v1/productos/generacodigo/',Genera_Codigo_Producto.as_view(),name='genera_codigo_producto'),

    #Api Cliente
    path('v1/clientes/',Cliente_Listado.as_view(),name='cliente_list'),

    #Api Compra
    path('v1/compra/generafactura/',Genera_Numero_factura_compra.as_view(),name='genera_numero_factura'),



]

app/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("",
         include(('bases.urls', 'bases'),
                 namespace='bases')),
    path("inventario/",
         include(('inventario.urls', 'inventario'),
                 namespace='inventario')),
    path("compra/",
         include(('compra.urls', 'compra'),
                 namespace='compra')),
    path("facturacion/",
         include(('facturacion.urls', 'facturacion'),
                 namespace='facturacion')),
    path("api/", include(('api.urls', 'api'),
                         namespace='api')),
    path('admin/', admin.site.urls),
]

compra/urls.py
from django.urls import path
from .views import Proveedores_Vista,Proveedor_Agregar, Proveedor_Editar , Proveedor_Inactivar, \
                   Compra_Vista,Compras,Compra_Detalle_Eliminar

from .reporte import reporte_compras, imprimir_compra 

urlpatterns = [
    #proveedores
    path('proveedores/', Proveedores_Vista.as_view(),name='proveedores'),
    path('proveedores/agregar', Proveedor_Agregar.as_view(),name='proveedor_agregar'),
    path('proveedores/editar/<int:pk>', Proveedor_Editar.as_view(),name='proveedor_editar'),
    path('proveedores/inactivar/<int:id>', Proveedor_Inactivar,name='proveedor_inactivar'),
    #compras
    path('compras/',Compra_Vista.as_view(),name='compras'),
    path('compras/nuevas',Compras,name='compras_nuevas'),
    path('compras/editar/<int:compra_id>',Compras,name='compras_editar'),
    path('compras/<int:compra_id>/eliminar/<int:pk>',Compra_Detalle_Eliminar.as_view(),name='compras_eliminar'),

    #reporte
    path('compras/imprimir',reporte_compras, name='imprimir_todas'),
    path('compras/<int:compra_id>/imprimir', imprimir_compra,name="imprimir"),
]

compra/models.py
from django.db import models
from bases.models import ClaseModelo
#Para los signals
from django.db.models.signals import post_save, post_delete
from django.dispatch import receiver

from django.db.models import Sum
from inventario.models import Producto

class Proveedor(ClaseModelo):
    descripcion = models.CharField(
        max_length=100,
        null=True, blank=True
        )
    direccion = models.CharField(
        max_length=250,
        null=True, blank=True
        )
    contacto = models.CharField(
        max_length=100,
        unique=True
    )
    telefono = models.CharField(
        max_length=10,
        null=True, blank=True
    )
    email = models.CharField(
        max_length=250,
        null=True, blank=True
    )

    def __str__(self):
        return '{}'.format(self.contacto)

    def save(self):
        self.contacto = self.contacto.upper()
        super(Proveedor, self).save()

    class Meta:
        verbose_name_plural = "Proveedores"



class Compras_Encabezado(ClaseModelo):
    fecha_compra=models.DateField(null=True,blank=True)
    observacion=models.TextField(blank=True,null=True)
    numero_factura=models.CharField(max_length=100)
    fecha_factura=models.DateField()
    sub_total=models.FloatField(default=0)
    descuento=models.FloatField(default=0)
    total=models.FloatField(default=0)

    proveedor=models.ForeignKey(Proveedor,on_delete=models.CASCADE)
    
    def __str__(self):
        return '{}'.format(self.observacion)

    def save(self):
        self.observacion = self.observacion.upper()
        if self.sub_total == None  or self.descuento == None:
            self.sub_total = 0
            self.descuento = 0
            
        self.total = self.sub_total - self.descuento
        super(Compras_Encabezado,self).save()

    class Meta:
        verbose_name_plural = "Encabezado Compras"
        verbose_name="Encabezado Compra"


class Compras_Detalle(ClaseModelo):
    compra=models.ForeignKey(Compras_Encabezado,on_delete=models.CASCADE)
    producto=models.ForeignKey(Producto,on_delete=models.CASCADE)
    cantidad=models.BigIntegerField(default=0)
    precio_prv=models.FloatField(default=0)
    sub_total=models.FloatField(default=0)
    descuento=models.FloatField(default=0)
    total=models.FloatField(default=0)
    costo=models.FloatField(default=0)

    def __str__(self):
        return '{}'.format(self.producto)

    def save(self):
        self.sub_total = float(float(int(self.cantidad)) * float(self.precio_prv))
        self.total = self.sub_total - float(self.descuento)
        super(Compras_Detalle, self).save()
    
    class Mega:
        verbose_name_plural = "Detalles Compras"
        verbose_name="Detalle Compra"


@receiver(post_delete, sender=Compras_Detalle)
def detalle_compra_borrar(sender,instance, **kwargs):
    id_producto = instance.producto.id
    id_compra = instance.compra.id

    compra_encabezado = Compras_Encabezado.objects.filter(pk=id_compra).first()
    if compra_encabezado:
        sub_total = Compras_Detalle.objects.filter(compra=id_compra).aggregate(Sum('sub_total'))
        descuento = Compras_Detalle.objects.filter(compra=id_compra).aggregate(Sum('descuento'))
        compra_encabezado.sub_total=sub_total['sub_total__sum']
        compra_encabezado.descuento=descuento['descuento__sum']
        compra_encabezado.save()
    
    producto=Producto.objects.filter(pk=id_producto).first()
    if producto:
        cantidad = int(producto.existencia) - int(instance.cantidad)
        producto.existencia = cantidad
        producto.save()


@receiver(post_save, sender=Compras_Detalle)
def detalle_compra_guardar(sender,instance,**kwargs):
    id_producto = instance.producto.id
    fecha_compra=instance.compra.fecha_compra

    producto=Producto.objects.filter(pk=id_producto).first()
    if producto:
        cantidad = int(producto.existencia) + int(instance.cantidad)
        producto.existencia = cantidad
        producto.ultima_compra=fecha_compra
        producto.save()




    

compra/forms.py
from django import forms

from .models import Proveedor, Compras_Encabezado

class Proveedor_Formulario(forms.ModelForm):
    email = forms.EmailField(max_length=254)
    class Meta:
        model=  Proveedor
        fields = ['contacto','telefono',"email","direccion","descripcion","estado"]
        labels= {
            "contacto": "Nombre",
            "telefono": "Telefono",
            "email": "Email",
            "direccion": "Direccion",
            "descripcion": "Nota",
            "estado":"Estado"
        }
        exclude = ['usuario_modificador','fecha_modificacion','usuario_creador','fecha_creacion']
        widget={'descripcion': forms.TextInput()}

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in iter(self.fields):
            self.fields[field].widget.attrs.update({
                'class': 'form-control'
            })

    def clean(self):
        try:
            proveedor = Proveedor.objects.get(
                contacto=self.cleaned_data["contacto"]
            )

            if not self.instance.pk:
                print("Registro ya existe")
                raise forms.ValidationError("Ya existe Proveedor con este nombre.")
            elif self.instance.pk!=proveedor.pk:
                print("Cambio no permitido")
                raise forms.ValidationError("Cambio No Permitido")
        except Proveedor.DoesNotExist:
            pass
        return self.cleaned_data

class Compras_Encabezado_Formulario(forms.ModelForm):
    fecha_compra = forms.DateInput()
    fecha_factura = forms.DateInput()
    
    class Meta:
        model= Compras_Encabezado
        fields=['proveedor','fecha_compra','observacion',
            'numero_factura','fecha_factura','sub_total',
            'descuento','total']

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in iter(self.fields):
            self.fields[field].widget.attrs.update({
                'class': 'form-control'
            })
        self.fields['fecha_compra'].widget.attrs['readonly'] = True
        self.fields['fecha_factura'].widget.attrs['readonly'] = True
        self.fields['sub_total'].widget.attrs['readonly'] = True
        self.fields['descuento'].widget.attrs['readonly'] = True
        self.fields['total'].widget.attrs['readonly'] = True
        self.fields['numero_factura'].widget.attrs['readonly'] = True
   

compra/views.py
from django.forms.models import BaseModelForm
from django.shortcuts import render, redirect
from django.views import generic
from django.http import HttpResponse, JsonResponse
import datetime
from django.contrib.auth.decorators import login_required, permission_required
from django.contrib import messages
from django.contrib.messages.views import SuccessMessageMixin
from django.urls import reverse_lazy

from django.db.models import Sum
from .models import Proveedor, Compras_Detalle, Compras_Encabezado
from .forms import Proveedor_Formulario, Compras_Encabezado_Formulario
from inventario.models import Producto
from bases.views import No_autorizado
from bases.utilitario import FormularioInvalido
import ipdb as debug

#Proveedores
class Proveedores_Vista(No_autorizado,generic.ListView):
    model = Proveedor
    template_name="compra/proveedores.html"
    context_object_name = 'proveedores'
    permission_required="compra.view_proveedor"


class Proveedor_Agregar(SuccessMessageMixin,FormularioInvalido,No_autorizado,generic.CreateView):
    model = Proveedor
    template_name="compra/proveedor_formulario.html"
    context_object_name = 'proveedor'
    permission_required="compra.add_proveedor"
    form_class = Proveedor_Formulario
    success_url= reverse_lazy('compra:proveedores')
    success_message="Provedor Agregado Correctamente"

    def form_valid(self, form):
       form.instance.usuario_creador = self.request.user
       return super().form_valid(form)
    


class Proveedor_Editar(SuccessMessageMixin,No_autorizado,FormularioInvalido,generic.UpdateView):
    model = Proveedor
    template_name="compra/proveedor_formulario.html"
    context_object_name = 'proveedor'
    permission_required="compra.change_proveedor"
    form_class = Proveedor_Formulario
    success_url= reverse_lazy('compra:proveedores')
    success_message="Provedor Editado Correctamente"

    def form_valid(self, form):
       form.instance.usuario_modificador = self.request.user.id
       return super().form_valid(form)
    

@login_required(login_url="bases:login")
@permission_required("inventario.delete_proveedor",login_url="bases:401.html")
def Proveedor_Inactivar(request, id):
    proveedor = Proveedor.objects.filter(pk =id).first()
    contexto ={}
    template_name ="compra/proveedor_inactivar.html"

    if not proveedor:
        return HttpResponse("Proveedor no existe " + str(id))
    
    if request.method =='GET':
        contexto = {'proveedor':proveedor}
    
    if request.method == 'POST':
        proveedor.estado = False
        proveedor.save()
        contexto ={'proveedor': 'Ok'}
        return HttpResponse("Proveedor Inactvo")
    
    return render(request, template_name,contexto)

#Compra
class Compra_Vista(No_autorizado,generic.ListView):
    model = Compras_Encabezado
    template_name="compra/compra_lista.html"
    context_object_name = 'compras'
    permission_required="compra.view_compras_detalle"


@login_required(login_url="bases:login")
@permission_required("compra.view_compras_detalle",login_url="bases:401.html")
def Compras(request, compra_id = None):
    template_name = "compra/compras.html"
    producto = Producto.objects.filter(estado = True)
    formulario_compras ={}
    contexto={}

    if request.method == 'GET':
        formulario_compras = Compras_Encabezado_Formulario()
        encabezado = Compras_Encabezado.objects.filter(pk=compra_id).first()

        if encabezado:
            detalle = Compras_Detalle.objects.filter(compra=encabezado)
            fecha_compra = datetime.date.isoformat(encabezado.fecha_compra)
            fecha_factura = datetime.date.isoformat(encabezado.fecha_factura)
            valores_mapeado = {
                'fecha_compra':fecha_compra,
                'proveedor': encabezado.proveedor,
                'observacion': encabezado.observacion,
                'numero_factura': encabezado.numero_factura,
                'fecha_factura': fecha_factura,
                'sub_total': encabezado.sub_total,
                'descuento': encabezado.descuento,
                'total':encabezado.total
            }
            formulario_compras = Compras_Encabezado_Formulario(valores_mapeado)
        else:
            detalle = None
        
        contexto = {
            "productos" : producto,
            "encabezado_compra": encabezado,
            "detalle_compra": detalle,
            "formulario_encabezado": formulario_compras
        }

    if request.method == 'POST':
        fecha_compra = request.POST.get("fecha_compra")
        observacion = request.POST.get("observacion")
        numero_factura = request.POST.get("numero_factura")
        fecha_factura = request.POST.get("fecha_factura")
        proveedor = request.POST.get("proveedor")
        sub_total = 0
        descuento = 0
        total = 0
        if not compra_id:
            prove=Proveedor.objects.get(pk=proveedor)

            encabezado = Compras_Encabezado(
                fecha_compra = fecha_compra,
                observacion = observacion,
                numero_factura = numero_factura,
                fecha_factura = fecha_factura,
                proveedor= prove,
                usuario_creador = request.user 
            )
            if encabezado:
                encabezado.save()
                compra_id = encabezado.id
        else:
            encabezado=Compras_Encabezado.objects.filter(pk=compra_id).first()
            if encabezado:
                encabezado.fecha_compra = fecha_compra
                encabezado.observacion = observacion
                encabezado.numero_factura=numero_factura
                encabezado.fecha_factura=fecha_factura
                encabezado.usuario_modificador=request.user.id
                encabezado.save()

        if not compra_id:
            return redirect("compra:compras")
        
        producto = request.POST.get("id_id_producto")
        cantidad = request.POST.get("id_cantidad_detalle")
        precio = request.POST.get("id_precio_detalle")
        sub_total_detalle = request.POST.get("id_sub_total_detalle")
        descuento_detalle  = request.POST.get("id_descuento_detalle")
        total_detalle  = request.POST.get("id_total_detalle")

        prod = Producto.objects.get(pk=producto)

        detalle = Compras_Detalle(
            compra = encabezado,
            producto = prod,
            cantidad = cantidad,
            precio_prv = precio,
            descuento = descuento_detalle,
            costo = 0,
            usuario_creador = request.user
        )

        if detalle:
            detalle.save()

            sub_total=Compras_Detalle.objects.filter(compra=compra_id).aggregate(Sum('sub_total'))
            descuento=Compras_Detalle.objects.filter(compra=compra_id).aggregate(Sum('descuento'))
            encabezado.sub_total = sub_total["sub_total__sum"]
            encabezado.descuento=descuento["descuento__sum"]
            encabezado.save()

        return redirect("compra:compras_editar",compra_id=compra_id)

    return render (request, template_name,contexto)




class Compra_Detalle_Eliminar(No_autorizado, generic.DeleteView):
    permission_required = "compra.delete_compras_detalle"
    model = Compras_Detalle
    template_name = "compra/compras_detalle_elimiinar.html"
    context_object_name = 'compra_detalle'
    
    def get_success_url(self):
          compra_id=self.kwargs['compra_id']
          return reverse_lazy('compra:compras_editar', kwargs={'compra_id': compra_id})

compra/templates/compra/compra_lista.html
{% extends 'app/base.html' %} {% block contenido %}
<div class="card shadow mb-4">
  <!-- Card Header - Dropdown -->
  <div
    class="card-header py-3 d-flex flex-row align-items-center justify-content-between"
  >
    <h6 class="m-0 font-weight-bold text-primary">Listado de Compra</h6>
    <div class="dropdown no-arrow">
      <a
        class="dropdown-toggle"
        href="#"
        role="button"
        id="dropdownMenuLink"
        data-toggle="dropdown"
        aria-haspopup="true"
        aria-expanded="false"
      >
        <i class="fas fa-ellipsis-v fa-sm fa-fw text-gray-400"></i>
      </a>
      <div
        class="dropdown-menu dropdown-menu-right shadow animated--fade-in"
        aria-labelledby="dropdownMenuLink"
      >
        <div class="dropdown-header">Acciones:</div>
        <a
          class="dropdown-item"
          href="{% url 'compra:imprimir_todas' %}"
          target="reportes"
          ><i class="fas fa-print"></i>Imprimir</a
        >
      </div>
    </div>
  </div>
  <!-- Card Body -->
  <div class="card-body">
    <div class="buttons-toolbar">
      <a class="btn btn-success" href="{% url 'compra:compras_nuevas' %}">
        <i cass="far fa-calendar-plus"></i> Nuevo
      </a>
    </div>
    <table
      id="table"
      data-toggle="table"
      data-pagination="true"
      data-search="true"
      data-show-columns="true"
      data-show-toggle="true"
      data-show-fullscreen="true"
      data-toolbar=".buttons-toolbar"
      data-locale="es-NI"
    >
      <thead>
        <th data-sortable="true">Fecha</th>
        <th data-sortable="true">Observación</th>
        <th data-sortable="true">No. Factura</th>
        <th data-sortable="true">F. Factura</th>
        <th data-sortable="true">Sub Total</th>
        <th data-sortable="true">Descuento</th>
        <th data-sortable="true">Total</th>
        <th data-sortable="true">Estado</th>
        <th class="all">Acciones</th>
      </thead>
      <tbody>
        {% for item in compras%}
        <tr>
          <td>{{ item.fecha_compra }}</td>
          <td>{{ item.observacion}}</td>
          <td>{{ item.numero_factura }}</td>
          <td>{{ item.fecha_factura }}</td>
          <td>{{ item.sub_total }}</td>
          <td>{{ item.descuento }}</td>
          <td>{{ item.total }}</td>
          <td>{{item.estado|yesno:"Activo,Inactivo"}}</td>
          <td>
            <button
              class="btn btn-warning btn-circle"
              onclick="return abrir_modal('{% url 'compra:compras_editar' item.id %}')"
            >
              <i class="far fa-edit"></i>
            </button>
            <a
              class="btn btn-success btn-circle"
              href="{% url 'compra:imprimir' item.id %}"
              target="reportes"
              ><i class="fas fa-print"></i
            ></a>
          </td>
        </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
</div>
{% endblock contenido %}

compra/templates/compra/compras_detalle_elimiinar.html
<div class="modal-dialog modal-lg">
    <div class="modal-content">
        <form role="form" action="{% url 'compra:compras_eliminar' compra_detalle.compra.id compra_detalle.pk %}" method="post"  class="form-inline">
            <div class="col-xl-12 col-md-12 mb-12">
                <div class="card border-left-danger shadow h-100 py-2">
                <div class="card-body">
                    <div class="row no-gutters align-items-center">
                    <div class="col mr-2">
                        <div class="text-xs font-weight-bold text-primary text-uppercase mb-1">
                            Eliminar Detalle
                        </div>
''                        <div class="dropdown-divider"></div>
                        {% csrf_token %}
                        <div class="row">
                            ¿Eliminar {{ compra_detalle.producto }} de compra número <b>{{ compra_detalle.compra.id}} </b> ?
                        </div>
                        <div class="dropdown-divider"></div>
                        <div class="row">
                            <div class="col">
                                <button type="submit" class="btn btn-danger"><span class="fa fa-save"></span>Eliminar</button>
                                <button type="button" class="btn btn-success" onclick="return cerrar_modal()">
                                        Cancelar
                                </button>
                            </div>
                        </div>
                    </div>
                    <div class="col-auto">
                        <i class="far fa-calendar-plus fa-2x text-gray-300"></i>
                    </div>
                    </div>
                </div>
                </div>
            </div>
        </form>
    </div>
</div> 

compra/templates/compra/proveedor_formulario.html
<div class="modal-dialog modal-lg">
    <div class="modal-content">
        {% if proveedor %}
        <form method="POST" role="form" class="form-inline" action="{% url 'compra:proveedor_editar' proveedor.id %}" enctype="multipart/form-data" >
        {% else %}
        <form method="POST" role="form" class="form-inline" action="{% url 'compra:proveedor_agregar' %}"  enctype="multipart/form-data" >
        {% endif %}
            <div class="col-md-12">
                {% if proveedor %}
                <div class="card border-left-warning shadow h-100 py-2">
                {% else %}
                <div class="card border-left-success shadow h-100 py-2">
                {% endif %}
                <div class="card-body">
                    
                    <div class="col-12">
                        <div class="text-xs font-weight-bold text-primary text-uppercase mb-1">
                          <h6>  {% if proveedor %} Editar {% else %} Nuevo {% endif %} Prooveedor </h6>
                        </div>
                        <div class="dropdown-divider"></div>
                        {% csrf_token %}
                        <div class="row">
                            <div class="column-6">
                                <div class="input-group">{{form.contacto.label}}</div>
                                <div class="input-group">{{form.contacto}}</div>
                            </div>
                            <div class="column-6">
                                <div class="input-group">{{form.telefono.label}}</div>
                                <div class="input-group">{{form.telefono}}</div>
                            </div> 
                        </div>
                        <div class="row">
                            <div class="column-6">
                                <div class="input-group">{{form.email.label}}</div>
                                <div class="input-group">{{form.email}}</div>
                            </div>
                            <div class="column-6">
                                <div class="input-group">{{form.direccion.label}}</div>
                                <div class="input-group">{{form.direccion}}</div>
                            </div> 
                        </div>
                        <div class="row">
                            <div class="column-6">
                                <div class="input-group">{{form.descripcion.label}}</div>
                                <div class="input-group">{{form.descripcion}}</div>
                            </div>
                            <div class="column-6">
                                <div class="input-group">{{form.estado.label}}</div>
                                <div class="input-group">{{form.estado}}</div>
                            </div> 
                        </div>
                        <hr/>
                        <div class="dropdown-divider"></div>
                        <div class="row">
                            <div class="col">
                                <button type="submit" class="btn btn-danger"><span class="fa fa-save"></span> Guardar</button>
                                <button type="button" class="btn btn-success" onclick="return cerrar_modal()">
                                    Cancelar
                                </button>
                            </div>
                        </div>
                    </div>
                  
                </div>
                </div>

            </div>
        </form>
    </div>
</div>

compra/templates/compra/proveedor_inactivar.html
<div class="modal-dialog modal-sm">
    <div class="modal-content">
        <form method="POST" class="form-inline">
            {% csrf_token %}
            <div class="col">
                <div class="card border-left-danger shadow h-100 py-2">
                  <div class="card-body">
                    <div class="row no-gutters align-items-center">
                      <div class="col mr-2">
                        <div class="text-xs font-weight-bold text-warning text-uppercase">
                            <div class="alert">
                                ¿ Inactivar <b>{{ proveedor.contacto }} </b> ?
                            </div>
                        </div>
                      </div>
                      <div class="row">
                        <button type="button" class="btn btn-danger" id="btn_Inactivar"><i class="far fa-question-circle"></i>
                          Inactivar
                        </button>
                        <button type="button" class="btn btn-success" onclick="return cerrar_modal()">
                            Cancelar
                        </button>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
        </form>
    </div>
  </div>
<script>
  $(document).ready(function(){

    $("#btn_Inactivar").click(function(e){
      e.preventDefault();
      var token = $('input[name=csrfmiddlewaretoken]').val();
      $.ajaxSetup({
        beforeSend: function(xhr, settings) {
            if (!(/^http:.*/.test(settings.url) || /^https:.*/.test(settings.url))) {
                xhr.setRequestHeader("X-CSRFToken", token);
            }
        }
      });
      var id = {{ proveedor.id }};
      var template="{% url 'compra:proveedor_inactivar' proveedor.id %}";
      var data = {"id":id};
      data = JSON.stringify(data);

      $.ajax({
        type: "POST",
        url: template,
        data: data,
        beforeSend: function(xhr,settings){
          $.ajaxSettings.beforeSend(xhr,settings);
        },
        success: function(response){
          cerrar_modal();
          var tipo=(response.startsWith('Proveedor no existe') ? 'red':'green' );
          Mensaje("Aviso",response,tipo)
        
        },
        error: function(jqXHR, textStatus, errorThrow){
          console.log(textStatus, errorThrow);
          cerrar_modal();
          Mensaje("error",errorThrow,"red")
        }
      });
     


    });
   
  
});
 </script>

compra/templates/compra/proveedores.html
{% extends 'app/base.html' %} {% block contenido %}
<div class="card shadow mb-4">
  <!-- Card Header - Dropdown -->
  <div
    class="card-header py-3 d-flex flex-row align-items-center justify-content-between"
  >
    <h4 class="m-0 font-weight-bold text-primary">Listado de Proveedor</h4>
  </div>
  <!-- Card Body -->
  <div class="card-body">
    <div class="buttons-toolbar">
      <button
        class="btn btn-success"
        onclick="return abrir_modal('{% url 'compra:proveedor_agregar'  %}')"
      >
        <i cass="far fa-calendar-plus"></i> Nuevo
      </button>
    </div>
    <table
      id="table"
      data-toggle="table"
      data-pagination="true"
      data-search="true"
      data-show-columns="true"
      data-show-toggle="true"
      data-show-fullscreen="true"
      data-toolbar=".buttons-toolbar"
      data-locale="es-NI"
    >
      <thead>
        <th>Contacto</th>
        <th>Dirección</th>
        <th>Teléfono</th>
        <th>EMail</th>
        <th>Descripcion</th>
        <th>Estado</th>
        <th class="all">Acciones</th>
      </thead>
      <tbody>
        {% for item in proveedores %}
        <tr>
          <td>{{ item.contacto }}</td>
          <td>{{ item.direccion}}</td>
          <td>{{ item.telefono }}</td>
          <td>{{ item.email }}</td>
          <td>{{ item.descripcion }}</td>
          <td>
            <div onclick="inactivar({{item.id}})">
              {% if item.estado %}
              <i class="far fa-thumbs-up text-primary"></i>
              {% else %}
              <i class="far fa-thumbs-down text-danger"></i>
              {% endif %}
            </div>
          </td>
          <td>
            <button
              class="btn btn-warning btn-circle"
              onclick="return abrir_modal('{% url 'compra:proveedor_editar' item.id %}')"
            >
              <i class="far fa-edit"></i>
            </button>
          </td>
        </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
</div>
{% endblock contenido %} {% block js %}
<script>
  function inactivar(id) {
    var data = { id: id };
    data = JSON.stringify(data);
    var token = "{{csrf_token}}";
    $.ajax({
      headers: { "X-CSRFToken": token },
      type: "POST",
      url: "/inventario/productos/estado/" + id,
      data: data,
      success: function (response) {
        if (response === "OK") {
          location.reload(true);
        } else {
          GestionarMensaje.MensajeInfo(
            "Aviso",
            "Error Intentado Cambiar Estado del Producto"
          );
        }
      },
      error: function (jqXHR, textStatus, errorThrow) {
        GestionarMensaje.MensajeError("Aviso", errorThrow, "red");
        cerrar_modal();
      },
    });
  }
</script>
{% endblock js %}