api/urls.py
from django.urls import path
from .views import Producto_Listado, Producto_Detalle, Cliente_Listado, \
                   Genera_Numero_factura_compra, Genera_Codigo_Producto
urlpatterns = [
    #Api Producto
    path('v1/productos/',Producto_Listado.as_view(),name='producto_listado'),
    path('v1/productos/<str:codigo>',Producto_Detalle.as_view(),name='producto_detalle'),
    path('v1/productos/generacodigo/',Genera_Codigo_Producto.as_view(),name='genera_codigo_producto'),

    #Api Cliente
    path('v1/clientes/',Cliente_Listado.as_view(),name='cliente_list'),

    #Api Compra
    path('v1/compra/generafactura/',Genera_Numero_factura_compra.as_view(),name='genera_numero_factura'),



]

app/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("",
         include(('bases.urls', 'bases'),
                 namespace='bases')),
    path("inventario/",
         include(('inventario.urls', 'inventario'),
                 namespace='inventario')),
    path("compra/",
         include(('compra.urls', 'compra'),
                 namespace='compra')),
    path("facturacion/",
         include(('facturacion.urls', 'facturacion'),
                 namespace='facturacion')),
    path("api/", include(('api.urls', 'api'),
                         namespace='api')),
    path('admin/', admin.site.urls),
]

inventario/urls.py
from django.urls import path
from .views import Categoria_Vista, Categoria_Agregar, Categoria_Editar,Categoria_Inactivar,\
                   SubCategoria_Vista, SubCategoria_Agregar , SubCategoria_Editar,SubCategoria_Inactivar, \
                   Marca_Vista, Marca_Agregar,Marca_Editar, Marca_Inactivar, \
                   Unidad_Medida_Vista,Unidad_Medidad_Agregar, Unidad_Medida_Editar, Unidad_Medida_Inactivar, \
                   Producto_Vista, Producto_Agregar,Producto_Editar,Producto_Inactivar

urlpatterns = [
    #Categorias
    path('categorias/', Categoria_Vista.as_view(), name='categorias'),
    path('categorias/agregar/', Categoria_Agregar.as_view(), name='categoria_agregar'),
    path('categorias/editar/<int:pk>/', Categoria_Editar.as_view(), name='categoria_editar'),
    path('categorias/estado/<int:id>', Categoria_Inactivar, name='categoria_inactivar'),

    #SubCategorias
    path('subcategorias/', SubCategoria_Vista.as_view(), name='subcategorias'),
    path('subcategorias/agregar/', SubCategoria_Agregar.as_view(), name='subcategoria_agregar'),
    path('subcategorias/editar/<int:pk>/', SubCategoria_Editar.as_view(), name='subcategoria_editar'),
    path('subcategorias/estado/<int:id>', SubCategoria_Inactivar, name='subcategoria_inactivar'),

    #Marcas
    path('marcas/', Marca_Vista.as_view(), name='marcas'),
    path('marcas/agregar/', Marca_Agregar.as_view(), name='marca_agregar'),
    path('marcas/editar/<int:pk>', Marca_Editar.as_view(), name='marca_editar'),
    path('marcas/estado/<int:id>', Marca_Inactivar, name='marca_inactivar'),

    #Unidad de Medida
    path('unidamedidas/', Unidad_Medida_Vista.as_view(), name='unidadmedidas'),
    path('unidamedidas/agregar/', Unidad_Medidad_Agregar.as_view(), name='unidadmedida_agregar'),
    path('unidamedidas/editar/<int:pk>', Unidad_Medida_Editar.as_view(), name='unidadmedida_editar'),
    path('unidamedidas/estado/<int:id>',Unidad_Medida_Inactivar, name='unidadmedida_inactivar'),

    #productos
    path('productos/', Producto_Vista.as_view(), name='productos'),
    path('productos/agregar', Producto_Agregar.as_view(), name='productos_agregar'),
    path('productos/editar/<int:pk>', Producto_Editar.as_view(), name='productos_editar'),
    path('productos/estado/<int:id>', Producto_Inactivar, name='productos_inactivar'),

]

facturacion/models.py
from django.db import models
from django.db.models.signals import post_save, post_delete
from django.dispatch import receiver
from django.db.models import Sum

from inventario.models import Producto
from bases.models import ClaseModelo, ClaseModelo2

class Cliente(ClaseModelo):
    FIS='Fisiica'
    EMP='Empresa'
    TIPO_CLIENTE = [
        (FIS,'Fisiica'),
        (EMP,'Empresa')
    ]
    nombres = models.CharField(
        max_length=100
    )
    apellidos = models.CharField(
        max_length=100
    )
    celular = models.CharField(
        max_length=20,
        null=True,
        blank=True
    )
    tipo=models.CharField(
        max_length=10,
        choices=TIPO_CLIENTE,
        default=FIS
    )

    def __str__(self):
        return '{} {}'.format(self.apellidos,self.nombres)

    def save(self, *args, **kwargs):
        self.nombres = self.nombres.upper()
        self.apellidos = self.apellidos.upper()
        super(Cliente, self).save( *args, **kwargs)

    class Meta:
        verbose_name_plural = "Clientes"


class Factura_Encabezado(ClaseModelo2):
    cliente = models.ForeignKey(Cliente, on_delete=models.CASCADE)
    fecha = models.DateTimeField(auto_now_add=True)
    sub_total=models.FloatField(default=0)
    descuento=models.FloatField(default=0)
    total=models.FloatField(default=0)

    def __str__(self):
        return '{}'.format(self.id)

    def save(self):
        self.total = self.sub_total - self.descuento
        super(Factura_Encabezado,self).save()

    class Meta:
        verbose_name_plural = "Encabezado Facturas"
        verbose_name="Encabezado Factura"
    

class Factura_Detalle(ClaseModelo2):
    factura = models.ForeignKey(Factura_Encabezado,on_delete=models.CASCADE)
    producto=models.ForeignKey(Producto,on_delete=models.CASCADE)
    cantidad=models.BigIntegerField(default=0)
    precio=models.FloatField(default=0)
    sub_total=models.FloatField(default=0)
    descuento=models.FloatField(default=0)
    total=models.FloatField(default=0)

    def __str__(self):
        return '{}'.format(self.producto)

    def save(self):
        self.sub_total = float(float(int(self.cantidad)) * float(self.precio))
        self.total = self.sub_total - float(self.descuento)
        super(Factura_Detalle, self).save()
    
    class Meta:
        verbose_name_plural = "Detalles Facturas"
        verbose_name="Detalle Factura"
        permissions = [
            ('supervisor_caja','Permisos de Supervisor de Caja Detalle')
        ]

      

@receiver(post_save, sender=Factura_Detalle)
def detalle_fac_guardar(sender,instance,**kwargs):
    factura_id = instance.factura.id
    producto_id = instance.producto.id

    factura_encabezado = Factura_Encabezado.objects.get(pk=factura_id)
    if factura_encabezado:
        sub_total = Factura_Detalle.objects.filter(factura=factura_id).aggregate(sub_total=Sum('sub_total')).get('sub_total',0.00)
        descuento = Factura_Detalle.objects.filter(factura=factura_id).aggregate(descuento=Sum('descuento')).get('descuento',0.00)  
        factura_encabezado.sub_total = sub_total
        factura_encabezado.descuento = descuento
        factura_encabezado.save()

    producto=Producto.objects.filter(pk=producto_id).first()
    if producto:
        cantidad = int(producto.existencia) - int(instance.cantidad)
        producto.existencia = cantidad
        producto.save()

inventario/models.py
from typing import Iterable, Optional
from django.db import models
from bases.models import ClaseModelo

#Modelo de categoria Heredando del modelo ClaseModelo(en el proyecto de Base)
#heredando de ClaseModelo campos id django lo coloca automaticamente
class Categoria(ClaseModelo):
    descripcion = models.CharField(
        max_length=100,
        help_text="Descripción del Categoria",
        unique=True)

    def __str__(self):
        return '{}'.format(self.descripcion)
 
    def save(self):
        self.descripcion = self.descripcion.upper()
        super(Categoria, self).save()

    class Meta:
        verbose_name_plural = "Categorias"


class SubCategoria(ClaseModelo):
    categoria = models.ForeignKey(Categoria,on_delete=models.CASCADE)
    descripcion = models.CharField(
        max_length=100,
        help_text="Descripcion de la Sub Categoria",
        unique=True
    )

    def __str__(self):
        return'{}:{}'.format(self.categoria.descripcion,self.descripcion)

    def save(self):
        self.descripcion = self.descripcion.upper()
        super(SubCategoria,self).save()
    
    class Meta:
        verbose_name_plural= "Sub Categorias"
        unique_together = ('categoria','descripcion')


class Marca(ClaseModelo):
    descripcion = models.CharField(
        max_length=100,
        help_text='Descripción de la Marca',
        unique=True
    )

    def __str__(self):
        return '{}'.format(self.descripcion)

    def save(self):
        self.descripcion = self.descripcion.upper()
        super(Marca, self).save()

    class Meta:
        verbose_name_plural = "Marca"


class UnidadMedida(ClaseModelo):
    descripcion = models.CharField(
        max_length=100,
        help_text='Descripción de la Unidad Medida',
        unique=True
    )

    def __str__(self):
        return '{}'.format(self.descripcion)

    def save(self):
        self.descripcion = self.descripcion.upper()
        super(UnidadMedida, self).save()

    class Meta:
        verbose_name_plural = "Unidades de Medida"



class Producto(ClaseModelo):
    codigo = models.CharField(
        max_length=20,
        unique=True
    )
    codigo_barra = models.CharField(max_length=50)
    descripcion = models.CharField(max_length=200)
    precio = models.FloatField(default=0)
    existencia = models.IntegerField(default=0)
    ultima_compra = models.DateField(null=True, blank=True)

    marca = models.ForeignKey(Marca, on_delete=models.CASCADE)
    unidad_medida = models.ForeignKey(UnidadMedida, on_delete=models.CASCADE)
    subcategoria = models.ForeignKey(SubCategoria, on_delete=models.CASCADE)

    def __str__(self):
        return '{}'.format(self.descripcion)
    
    def save(self):
        self.descripcion = self.descripcion.upper()
        super(Producto,self).save()
    
    class Meta:
        verbose_name_plural = "Productos"
        unique_together = ('codigo','codigo_barra')

inventario/forms.py
from django import forms

from .models import Categoria,SubCategoria,Marca,UnidadMedida,Producto


class CategoriaFormulario(forms.ModelForm):
    class Meta:
        model = Categoria
        fields = ["descripcion","estado"]
        labels ={
            "descripcion":"Categoria",
            "estado":"Estado"
            }
        widgets = {
            "descripcion": forms.TextInput()
        }
    def __init__(self, *args, **kwargs):
        super(CategoriaFormulario, self).__init__(*args, **kwargs)
        for field in iter(self.fields):
          self.fields[field].widget.attrs.update({
              'class':'form-control'
          })


class SubCategoriaFormulario(forms.ModelForm):
    categoria = forms.ModelChoiceField(
        queryset= Categoria.objects.filter(estado=True).order_by('descripcion')
    )
    class Meta:
        model = SubCategoria
        fields = ["categoria","descripcion","estado"]
        labels ={
                "categoria": "Categoria",
                "descripcion":"Sub Categoria",
                "estado":"Estado"}
        widgets = {
            "descripcion": forms.TextInput()
        }
    def __init__(self, *args, **kwargs):
        super(SubCategoriaFormulario, self).__init__(*args, **kwargs)
        for field in iter(self.fields):
          self.fields[field].widget.attrs.update({
              'class':'form-control'
          })
        self.fields['categoria'].empty_label= "seleccione"


class MarcaFormulario(forms.ModelForm):
    class Meta:
        model=Marca
        fields = ['descripcion','estado']
        labels= {
            "descripcion": "Nombre",
            "estado":"Estado"}
        widget={'descripcion': forms.TextInput()}

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in iter(self.fields):
            self.fields[field].widget.attrs.update({
                'class': 'form-control'
            })



class UnidadMedidaFormulario(forms.ModelForm):
    class Meta:
        model=UnidadMedida
        fields = ['descripcion','estado']
        labels= {'descripcion': "Descripción de la Marca",
                "estado":"Estado"}
        widget={'descripcion': forms.TextInput()}

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in iter(self.fields):
            self.fields[field].widget.attrs.update({
                'class': 'form-control'
            })

class Producto_Formulario(forms.ModelForm):
    class Meta:
        model= Producto
        fields=['codigo','codigo_barra','descripcion','estado', \
                'precio','existencia','ultima_compra',
                'marca','subcategoria','unidad_medida']
        exclude = ['usuario_modificador','fecha_modificacion','usuario_creador','usuario_modificador']
        widget={'descripcion': forms.TextInput()}

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in iter(self.fields):
            self.fields[field].widget.attrs.update({
                'class': 'form-control'
            })
        self.fields['ultima_compra'].widget.attrs['readonly'] = True
        self.fields['existencia'].widget.attrs['readonly'] = True
        self.fields['codigo'].widget.attrs['readonly'] = True

inventario/templates/inventario/categoria_formulario.html
<div class="modal-dialog modal-lg">
    <div class="modal-content">
        {% if categoria %}
        <form method="POST" role="form" class="form-inline" action="{% url 'inventario:categoria_editar' categoria.id %}" enctype="multipart/form-data" >
        {% else %}
        <form method="POST" role="form" class="form-inline" action="{% url 'inventario:categoria_agregar' %}"  enctype="multipart/form-data" >
        {% endif %}
            <div class="col-md-12">
                {% if categoria %}
                <div class="card border-left-warning shadow h-100 py-2">
                {% else %}
                <div class="card border-left-success shadow h-100 py-2">
                {% endif %}
                <div class="card-body">
                    
                    <div class="col-12">
                        <div class="text-xs font-weight-bold text-primary text-uppercase mb-1">
                          <h6>  {% if categoria %} Editar {% else %} Nueva {% endif %} Categoria </h6>
                        </div>
                        <div class="dropdown-divider"></div>
                        {% csrf_token %}
                        <div class="row">
                            <div class="column-6">
                                <div class="input-group">{{form.descripcion.label}}</div>
                                <div class="input-group">{{form.descripcion}}</div>
                            </div>
                            <div class="column-6">
                                <div class="input-group">{{form.estado.label}}</div>
                                <div class="input-group">{{form.estado}}</div>
                            </div> 
                        </div>
                        <hr/>
                        <div class="dropdown-divider"></div>
                        <div class="row">
                            <div class="col">
                                <button type="submit" class="btn btn-danger"><span class="fa fa-save"></span> Guardar</button>
                                <button type="button" class="btn btn-success" onclick="return cerrar_modal()">
                                    Cancelar
                                </button>
                            </div>
                        </div>
                    </div>
                  
                </div>
                </div>

            </div>
        </form>
    </div>
</div>

inventario/templates/inventario/categorias.html
{% extends 'app/base.html' %} {% block contenido %}
<!-- Dropdown Card Example -->
<div class="card shadow mb-4">
  <!-- Card Header - Dropdown -->
  <div
    class="card-header py-3 d-flex flex-row align-items-center justify-content-between"
  >
    <h4 class="m-0 font-weight-bold text-primary">Listado de Categoria</h4>
  </div>
  <!-- Card Body -->
  <div class="card-body">
    <div class="buttons-toolbar">
      <button
        class="btn btn-success"
        onclick="return abrir_modal('{% url 'inventario:categoria_agregar' %}')"
      >
        <i cass="far fa-calendar-plus"></i> Nuevo
      </button>
    </div>
    <table
      id="table"
      data-toggle="table"
      data-pagination="true"
      data-search="true"
      data-show-columns="true"
      data-show-toggle="true"
      data-show-fullscreen="true"
      data-toolbar=".buttons-toolbar"
      data-locale="es-NI"
    >
      <thead>
        <th data-sortable="true" data-field="Descripcion">Descripción</th>
        <th data-sortable="true" data-field="estado">Estado</th>
        <th data-sortable="true" data-field="fecha creacion">Fecha Creado</th>
        <th data-sortable="true" data-field="fecha modificacion">
          Fecha Modificada.
        </th>
        <th class="all">Acciones</th>
      </thead>
      <tbody>
        {% for item in categorias %}
        <tr>
          <td>{{ item.descripcion }}</td>
          <td>
            <div onclick="inactivar({{item.id}})">
              {% if item.estado %}
              <i class="far fa-thumbs-up text-primary"></i>
              {% else %}
              <i class="far fa-thumbs-down text-danger"></i>
              {% endif %}
            </div>
          </td>
          <td>{{ item.fecha_creacion|date:"d/m/Y H:i:s" }}</td>
          <td>{{ item.fecha_modificacion|date:"d/m/Y H:i:s" }}</td>
          <td>
            <button
              onclick="return abrir_modal('{% url 'inventario:categoria_editar' item.id %}')"
              class="btn btn-warning btn-circle"
              role="button"
            >
              <i class="far fa-edit"></i>
            </button>
          </td>
        </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
</div>
{% endblock contenido %} {% block js %}
<script>
  function inactivar(id) {
    var data = { id: id };
    data = JSON.stringify(data);
    var token = "{{csrf_token}}";
    $.ajax({
      headers: { "X-CSRFToken": token },
      type: "POST",
      url: "/inventario/categorias/estado/" + id,
      data: data,
      success: function (response) {
        if (response === "OK") {
          location.reload(true);
        } else {
          GestionarMensaje.MensajeInfo(
            "Aviso",
            "Error Intentado Cambiar Estado a la Categoria"
          );
        }
      },
      error: function (jqXHR, textStatus, errorThrow) {
        GestionarMensaje.MensajeError("Aviso", errorThrow, "red");
        cerrar_modal();
      },
    });
  }
</script>
{% endblock js %}

inventario/templates/inventario/marca_formulario.html
<div class="modal-dialog modal-lg">
    <div class="modal-content">
        {% if marca %}
        <form method="POST" role="form" class="form-inline" action="{% url 'inventario:marca_editar' marca.id %}" enctype="multipart/form-data" >
        {% else %}
        <form method="POST" role="form" class="form-inline" action="{% url 'inventario:marca_agregar' %}"  enctype="multipart/form-data" >
        {% endif %}
            <div class="col-md-12">
                {% if marca %}
                <div class="card border-left-warning shadow h-100 py-2">
                {% else %}
                <div class="card border-left-success shadow h-100 py-2">
                {% endif %}
                <div class="card-body">
                    
                    <div class="col-12">
                        <div class="text-xs font-weight-bold text-primary text-uppercase mb-1">
                           <h5> {% if marca %} Editar {% else %} Nueva {% endif %} Marca </h5>
                        </div>
                        <div class="dropdown-divider"></div>
                        {% csrf_token %}
                        <div class="row">
                            <div class="column-6">
                                <div class="input-group">{{form.descripcion.label}}</div>
                                <div class="input-group">{{form.descripcion}}</div>
                            </div>
                            <div class="column-6">
                                <div class="input-group">{{form.estado.label}}</div>
                                <div class="input-group">{{form.estado}}</div>
                            </div> 
                        </div>
                        <hr/>
                        <div class="dropdown-divider"></div>
                        <div class="row">
                            <div class="col">
                                <button type="submit" class="btn btn-danger"><span class="fa fa-save"></span> Guardar</button>
                                <button type="button" class="btn btn-success" onclick="return cerrar_modal()">
                                    Cancelar
                                </button>
                            </div>
                        </div>
                    </div>
                  
                </div>
                </div>

            </div>
        </form>
    </div>
</div>

inventario/templates/inventario/marcas.html
{% extends 'app/base.html' %} {% block contenido %}
<!-- Dropdown Card Example -->
<div class="card shadow mb-4">
  <div
    class="card-header py-3 d-flex flex-row align-items-center justify-content-between"
  >
    <h4 class="m-0 font-weight-bold text-primary">Listado de Marca</h4>
  </div>
  <!-- Card Body -->
  <div class="card-body">
    <div class="buttons-toolbar">
      <button
        class="btn btn-success"
        onclick="return abrir_modal('{% url 'inventario:marca_agregar' %}')"
      >
        <i cass="far fa-calendar-plus"></i> Nuevo
      </button>
    </div>
    <table
      id="table"
      data-toggle="table"
      data-pagination="true"
      data-search="true"
      data-show-columns="true"
      data-show-toggle="true"
      data-show-fullscreen="true"
      data-toolbar=".buttons-toolbar"
      data-locale="es-NI"
    >
      <thead>
        <th data-sortable="true" data-field="Descripcion">Descripción</th>
        <th data-sortable="true" data-field="Estado">Estado</th>
        <th data-sortable="true" data-field="fecha_creacion">
          Feecha Creacion
        </th>
        <th data-sortable="true" data-field="fecha_modificacion">
          Fecha Modificacion
        </th>
        <th class="all">Acciones</th>
      </thead>
      <tbody>
        {% for item in marcas %}
        <tr>
          <td>{{ item.descripcion }}</td>
          <td>
            <div onclick="inactivar({{item.id}})">
              {% if item.estado %}
              <i class="far fa-thumbs-up text-primary"></i>
              {% else %}
              <i class="far fa-thumbs-down text-danger"></i>
              {% endif %}
            </div>
          </td>
          <td>{{ item.fecha_creacion|date:"d/m/Y H:i:s" }}</td>
          <td>{{ item.fecha_modificacion|date:"d/m/Y H:i:s" }}</td>
          <td>
            <button
              onclick="return abrir_modal('{% url 'inventario:marca_editar' item.id %}')"
              class="btn btn-warning btn-circle"
            >
              <i class="far fa-edit"></i>
            </button>
          </td>
        </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
</div>
{% endblock contenido %} {% block js %}
<script>
  function inactivar(id) {
    var data = { id: id };
    data = JSON.stringify(data);
    var token = "{{csrf_token}}";
    $.ajax({
      headers: { "X-CSRFToken": token },
      type: "POST",
      url: "/inventario/marcas/estado/" + id,
      data: data,
      success: function (response) {
        if (response === "OK") {
          location.reload(true);
        } else {
          GestionarMensaje.MensajeInfo(
            "Aviso",
            "Error Intentado Cambiar Estado a la Marca"
          );
        }
      },
      error: function (jqXHR, textStatus, errorThrow) {
        GestionarMensaje.MensajeError("Aviso", errorThrow, "red");
        cerrar_modal();
      },
    });
  }
</script>
{% endblock js %}

inventario/templates/inventario/producto_formulario.html
<div class="modal-dialog modal-lg">
    <div class="modal-content">
        {% if producto %}
        <form method="POST" role="form" class="form-inline" action="{% url 'inventario:productos_editar' producto.id %}" enctype="multipart/form-data" >
        {% else %}
        <form method="POST" role="form" class="form-inline" action="{% url 'inventario:productos_agregar' %}"  enctype="multipart/form-data" >
        {% endif %}
            <div class="col-md-12">
                {% if producto %}
                <div class="card border-left-warning shadow h-100 py-2">
                {% else %}
                <div class="card border-left-success shadow h-100 py-2">
                {% endif %}
                <div class="card-body">           
                    <div class="col-12">
                        <div class="text-xs font-weight-bold text-primary text-uppercase mb-1">
                           <h5> {% if producto %} Editar {% else %} Nueva {% endif %} Productos </h5>
                        </div>
                        <div class="dropdown-divider"></div>
                        {% csrf_token %}
                        <input type="hidden" id="id_producto" value="{{producto.pk}}" />
                        <div class="row">
                            <div class="column-6">
                                <div class="input-group">{{form.codigo.label}}</div>
                                <div class="input-group">{{form.codigo}}</div>
                            </div>
                            <div class="column-6">
                                <div class="input-group">{{form.codigo_barra.label}}</div>
                                <div class="input-group">{{form.codigo_barra}}</div>    
                            </div>                            
                        </div>
                        <div class="row">
                            <div class="column-6">
                                <div class="input-group">{{form.descripcion.label}}</div>
                                <div class="input-group">{{form.descripcion}}</div>
                            </div>
                            <div class="column-6">
                                <div class="input-group">{{form.estado.label}}</div>
                                <div class="input-group">{{form.estado}}</div>    
                            </div>                            
                        </div>
                        
                        <div class="row">
                            <div class="column-6">
                                <div class="input-group">{{form.precio.label}}</div>
                                <div class="input-group">{{form.precio}}</div>
                            </div>
                            <div class="column-6">
                                <div class="input-group">{{form.existencia.label}}</div>
                                <div class="input-group">{{form.existencia}}</div>    
                            </div>                            
                        </div>

                        <div class="row">
                            <div class="column-6">
                                <div class="input-group">{{form.ultima_compra.label}}</div>
                                <div class="input-group">{{form.ultima_compra}}</div>
                            </div>
                            <div class="column-6">
                                <div class="input-group">{{form.marca.label}}</div>
                                <div class="input-group">{{form.marca}}</div>    
                            </div>     
                                          
                        </div>

                        <div class="row">
                            <div class="column-6">
                                <div class="input-group">{{form.unidad_medida.label}}</div>
                                <div class="input-group">{{form.unidad_medida}}</div>    
                            </div>         
                            <div class="column-6">
                                <div class="input-group">Categoría</div>
                                <div class="input-group">
                                    <select name="categoria" id="id_categoria" class="form-control">
                                        <option value="0">-------</option>
                                        {% for item in categorias %}
                                        <option value="{{item.id}}">{{item.descripcion}}</option>
                                        {% endfor%}
                                    </select>
                                </div>
                            </div>                    
                        </div>
                        <div class="row">
                            <div class="column-6">
                                <div class="input-group">Sub Categoría</div>
                                <div class="input-group">
                                    <select name="subcategoria" id="id_subcategoria" class="form-control from-control-sm">
                                        <option value="0">-------</option>
                                        {% for item in subcategorias %}
                                        <option value="{{item.id}}" data-chained="{{item.categoria.id}}">{{item.descripcion}}</option>
                                        {% endfor%}
                                    </select>
                                </div>
                            </div>     
                        </div>
                        
                        <hr/>
                        <div class="dropdown-divider"></div>
                        <div class="row">
                            <div class="col">
                                <button type="submit" class="btn btn-danger"><span class="fa fa-save"></span> Guardar</button>
                                <button type="button" class="btn btn-success" onclick="return cerrar_modal()">
                                    Cancelar
                                </button>
                            </div>
                        </div>
                    </div>
                  
                </div>
                </div>

            </div>
        </form>
    </div>
</div>





<script>
    $(function() {
        $("#id_categoria").val("{{ producto.subcategoria.categoria.id }}").change();
        $("#id_subcategoria").val("{{ producto.subcategoria.id }}").change();
        $("#id_subcategoria").chained("#id_categoria");

        if ($("#id_producto").val()==0 || $("#id_producto").val()=="" || $("#id_producto").val()==null)
        {
           $.ajax({
            type:"GET",
            url: "{% url 'api:genera_codigo_producto' %}",
            success: function(data){
                $("#id_codigo").val(data)
            }
           })
        
        }
    });
</script>