api/urls.py
from django.urls import path
from .views import Producto_Listado, Producto_Detalle, Cliente_Listado, \
                   Genera_Numero_factura_compra, Genera_Codigo_Producto
urlpatterns = [
    #Api Producto
    path('v1/productos/',Producto_Listado.as_view(),name='producto_listado'),
    path('v1/productos/<str:codigo>',Producto_Detalle.as_view(),name='producto_detalle'),
    path('v1/productos/generacodigo/',Genera_Codigo_Producto.as_view(),name='genera_codigo_producto'),

    #Api Cliente
    path('v1/clientes/',Cliente_Listado.as_view(),name='cliente_list'),

    #Api Compra
    path('v1/compra/generafactura/',Genera_Numero_factura_compra.as_view(),name='genera_numero_factura'),



]

app/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("",
         include(('bases.urls', 'bases'),
                 namespace='bases')),
    path("inventario/",
         include(('inventario.urls', 'inventario'),
                 namespace='inventario')),
    path("compra/",
         include(('compra.urls', 'compra'),
                 namespace='compra')),
    path("facturacion/",
         include(('facturacion.urls', 'facturacion'),
                 namespace='facturacion')),
    path("api/", include(('api.urls', 'api'),
                         namespace='api')),
    path('admin/', admin.site.urls),
]

facturacion/urls.py
from django.urls import path
from .views import Clientes_Vista, Cliente_Agregar, Cliente_Editar, cliente_Inactivar ,\
        Facturas_vista, facturas, Producto_vista, borrar_detalle_factura

from .reporte import imprimir_factura_recibo, imprimir_todas_factura

urlpatterns = [
    #cliente
    path('cliente/',Clientes_Vista.as_view(),name="clientes"),
    path('cliente/agregar',Cliente_Agregar.as_view(),name="cliente_agregar"),
    path('cliente/editar/<int:pk>',Cliente_Editar.as_view(),name="cliente_editar"),
    path('cliente/estado/<int:id>',cliente_Inactivar,name="cliente_inactivar"),
    #factura
    path('facturas/',Facturas_vista.as_view(),name="facturas_lista"),
    path('facturas/agregar',facturas,name="facturas_agregar"),
    path('facturas/editar/<int:id>',facturas, name="factura_editar"),
    path('facturas/borrar_detalle/<int:id>',borrar_detalle_factura, name="factura_borrar_detalle"),
    path('facturas/buscar-producto',Producto_vista.as_view(), name="factura_producto"),
    path('facturas/imprimir/<int:id>',imprimir_factura_recibo, name="factura_imprimir_una"),
    path('facturas/imprimir-todas/<str:fechainicio>/<str:fechafinal>',imprimir_todas_factura, name="factura_imprimir_todas"),


]

facturacion/models.py
from django.db import models
from django.db.models.signals import post_save, post_delete
from django.dispatch import receiver
from django.db.models import Sum

from inventario.models import Producto
from bases.models import ClaseModelo, ClaseModelo2

class Cliente(ClaseModelo):
    FIS='Fisiica'
    EMP='Empresa'
    TIPO_CLIENTE = [
        (FIS,'Fisiica'),
        (EMP,'Empresa')
    ]
    nombres = models.CharField(
        max_length=100
    )
    apellidos = models.CharField(
        max_length=100
    )
    celular = models.CharField(
        max_length=20,
        null=True,
        blank=True
    )
    tipo=models.CharField(
        max_length=10,
        choices=TIPO_CLIENTE,
        default=FIS
    )

    def __str__(self):
        return '{} {}'.format(self.apellidos,self.nombres)

    def save(self, *args, **kwargs):
        self.nombres = self.nombres.upper()
        self.apellidos = self.apellidos.upper()
        super(Cliente, self).save( *args, **kwargs)

    class Meta:
        verbose_name_plural = "Clientes"


class Factura_Encabezado(ClaseModelo2):
    cliente = models.ForeignKey(Cliente, on_delete=models.CASCADE)
    fecha = models.DateTimeField(auto_now_add=True)
    sub_total=models.FloatField(default=0)
    descuento=models.FloatField(default=0)
    total=models.FloatField(default=0)

    def __str__(self):
        return '{}'.format(self.id)

    def save(self):
        self.total = self.sub_total - self.descuento
        super(Factura_Encabezado,self).save()

    class Meta:
        verbose_name_plural = "Encabezado Facturas"
        verbose_name="Encabezado Factura"
    

class Factura_Detalle(ClaseModelo2):
    factura = models.ForeignKey(Factura_Encabezado,on_delete=models.CASCADE)
    producto=models.ForeignKey(Producto,on_delete=models.CASCADE)
    cantidad=models.BigIntegerField(default=0)
    precio=models.FloatField(default=0)
    sub_total=models.FloatField(default=0)
    descuento=models.FloatField(default=0)
    total=models.FloatField(default=0)

    def __str__(self):
        return '{}'.format(self.producto)

    def save(self):
        self.sub_total = float(float(int(self.cantidad)) * float(self.precio))
        self.total = self.sub_total - float(self.descuento)
        super(Factura_Detalle, self).save()
    
    class Meta:
        verbose_name_plural = "Detalles Facturas"
        verbose_name="Detalle Factura"
        permissions = [
            ('supervisor_caja','Permisos de Supervisor de Caja Detalle')
        ]

      

@receiver(post_save, sender=Factura_Detalle)
def detalle_fac_guardar(sender,instance,**kwargs):
    factura_id = instance.factura.id
    producto_id = instance.producto.id

    factura_encabezado = Factura_Encabezado.objects.get(pk=factura_id)
    if factura_encabezado:
        sub_total = Factura_Detalle.objects.filter(factura=factura_id).aggregate(sub_total=Sum('sub_total')).get('sub_total',0.00)
        descuento = Factura_Detalle.objects.filter(factura=factura_id).aggregate(descuento=Sum('descuento')).get('descuento',0.00)  
        factura_encabezado.sub_total = sub_total
        factura_encabezado.descuento = descuento
        factura_encabezado.save()

    producto=Producto.objects.filter(pk=producto_id).first()
    if producto:
        cantidad = int(producto.existencia) - int(instance.cantidad)
        producto.existencia = cantidad
        producto.save()

facturacion/forms.py
from django import forms

from .models import Cliente
class Cliente_Formulario(forms.ModelForm):
    class Meta:
        model=Cliente
        fields=['nombres','apellidos','tipo','celular','estado']
        labels={
            "nombres": "Nombres",
            "apellidos": "Apellidos",
            "tipo": "Tipo Cliente",
            "celular": "Celular",
            "estado":"Estado"
        }
        exclude = ['usuario_modificador','fecha_modificacion','usuario_creador','fecha_creacion']

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in iter(self.fields):
            self.fields[field].widget.attrs.update({
                'class': 'form-control'
            })

facturacion/views.py
from django.shortcuts import render,redirect
from django.views import generic
from django.contrib.messages.views import SuccessMessageMixin
from django.contrib import messages
from datetime import datetime
from django.contrib.auth.decorators import login_required, permission_required
from django.contrib.auth import authenticate
from django.http import HttpResponse
from django.urls import reverse_lazy
from django.contrib import messages
from bases.views import No_autorizado
from inventario.models import Producto
import inventario.views as inventario

from .models import Cliente, Factura_Encabezado, Factura_Detalle
from .forms import Cliente_Formulario
#Clientes
class Clientes_Vista(No_autorizado,generic.ListView):
    model = Cliente
    template_name="facturacion/clientes.html"
    context_object_name = 'clientes'
    permission_required="facturacion.view_cliente"


class Cliente_Agregar(SuccessMessageMixin,No_autorizado,generic.CreateView):
    model=Cliente
    template_name="facturacion/cliente_formulario.html"
    context_object_name = 'cliente'
    success_message="Registro Agregado Satisfactoriamente"
    form_class= Cliente_Formulario
    success_url= reverse_lazy("facturacion:clientes")
    permission_required="facturacion.add_cliente"

    def get(self, request, *args, **kwargs):
        print("sobre escribir get")
        
        try:
            t = request.GET["t"]
        except:
            t = None

        print(t)
        
        form = self.form_class(initial=self.initial)
        return render(request, self.template_name, {'form': form, 't':t})
    
    def form_valid(self, form):
       form.instance.usuario_creador = self.request.user
       return super().form_valid(form)


class Cliente_Editar(SuccessMessageMixin,No_autorizado, generic.UpdateView):
    model = Cliente
    template_name="facturacion/cliente_formulario.html"
    form_class=Cliente_Formulario
    success_url= reverse_lazy("facturacion:clientes")
    context_object_name = 'cliente'
    permission_required="facturacion.change_cliente"
    success_message = "Cliente Modificado Correctamente"
 
    def form_valid(self, form):
       form.instance.usuario_modificador = self.request.user.id
       return super().form_valid(form)


@login_required(login_url="/login/")
@permission_required("facturacion.change_cliente",login_url="/login/")
def cliente_Inactivar(request,id):
    cliente = Cliente.objects.filter(pk=id).first()

    if request.method=="POST":
        if cliente:
            cliente.estado = not cliente.estado
            cliente.save()
            return HttpResponse("OK")
        return HttpResponse("FAIL")
    
    return HttpResponse("FAIL")


class Facturas_vista(No_autorizado, generic.ListView):
    model = Factura_Encabezado
    template_name = "facturacion/facturas_listado.html"
    context_object_name = "facturas"
    permission_required="facturacion.view_factura_encabezado"


@login_required(login_url='bases:login')
@permission_required('facturacion.change_factura_encabezado', login_url='bases:401.html')
def facturas(request,id=None):
    template_name='facturacion/facturas.html'

    factura_detalle = {}
    factura_encabezado ={}
    
    clientes = Cliente.objects.filter(estado=True)
    if request.method == 'GET':
        encabezado = Factura_Encabezado.objects.filter(pk=id).first()
        if not encabezado:
            factura_encabezado ={
                "id":0,
                "fecha":datetime.today(),
                "cliente":0,
                'sub_total':0.00,
                'descuento':0.00,
                'total': 0.00
            }
            factura_detalle = None
        else:
            factura_encabezado ={
                "id":encabezado.id,
                "fecha":encabezado.fecha,
                "cliente":encabezado.cliente,
                'sub_total':encabezado.sub_total,
                'descuento':encabezado.descuento,
                'total': encabezado.total
            }
            factura_detalle = Factura_Detalle.objects.filter(factura=encabezado)

        contexto ={
            "factura_encabezado":factura_encabezado,
            "factura_detalle":factura_detalle,
            "clientes":clientes 
            }
        print(contexto.get("factura_encabezado"))
        return render(request,template_name,contexto)
    if request.method == 'POST':
        idcliente = request.POST.get("factura_encabezado_cliente")
        fecha  = request.POST.get("factura_encabezado_fecha")
        cliente = Cliente.objects.filter(pk=idcliente).first()
        if not id:
            factura_encabezado = Factura_Encabezado(
                cliente = cliente,
                fecha = fecha
            )
            if factura_encabezado:
                factura_encabezado.save()
                id = factura_encabezado.id
        else:
            factura_encabezado = Factura_Encabezado.objects.filter(pk=id).first()
            if factura_encabezado:
                factura_encabezado.cliente = cliente
                factura_encabezado.save()
        if not id:
            messages.error(request,'No Puedo Continuar No Pude Detectar No. de Factura')
            return redirect("facturacion:facturas_listado")
        codigo = request.POST.get("codigo")
        cantidad = request.POST.get("cantidad")
        precio = request.POST.get("precio")
        s_total = request.POST.get("sub_total_detalle")
        descuento = request.POST.get("descuento_detalle")
        total = request.POST.get("total_detalle")

        prod = Producto.objects.get(codigo=codigo)
        factura_detalle = Factura_Detalle(
            factura = factura_encabezado,
            producto = prod,
            cantidad = cantidad,
            precio = precio,
            sub_total = s_total,
            descuento = descuento,
            total = total
        )
        
        if factura_detalle:
            factura_detalle.save()
        
        return redirect("facturacion:factura_editar",id=id)

 
class Producto_vista(inventario.Producto_Vista):
    template_name ="facturacion/buscar_producto.html"


def borrar_detalle_factura(request, id):
    template_name = "facturacion/factura_borrar_datalle.html"

    factura_detalle = Factura_Detalle.objects.get(pk=id)

    if request.method=="GET":
        context={"factura_detalle":factura_detalle}

    if request.method == "POST":
        usr = request.POST.get("usuario")
        pas = request.POST.get("pass")

        user =authenticate(username=usr,password=pas)

        if not user:
            return HttpResponse("Usuario o Clave Incorrecta")
        
        if not user.is_active:
            return HttpResponse("Usuario Inactivo")

        if user.is_superuser or user.has_perm("facturacion.supervisor_caja"):
            factura_detalle.id = None
            factura_detalle.cantidad = (-1 * factura_detalle.cantidad)
            factura_detalle.sub_total = (-1 * factura_detalle.sub_total)
            factura_detalle.descuento = (-1 * factura_detalle.descuento)
            factura_detalle.total = (-1 * factura_detalle.total)
            factura_detalle.save()

            return HttpResponse("ok")

        return HttpResponse("Usuario no autorizado")
    
    return render(request,template_name,context)

facturacion/templates/facturacion/buscar_producto.html
<div class="modal-dialog modal-lg">
    <div class="modal-content">
        <div class="col-xl-12 col-md-12 mb-12">
            <div class="card border-left-warning shadow h-100 py-2">
                <div class="card-body">
                    <div class="row no-gutters align-items-center">
                    <div class="col mr-2">
                        <div class="text-xs font-weight-bold text-primary text-uppercase mb-1">
                            Buscar Producto
                        </div>
                        <div class="dropdown-divider"></div>
                        
                        <div class="row">
                                <table
                                id="tblProducto"
                                data-pagination="true"
                                data-search="true"
                                data-show-columns="true"
                                data-show-fullscreen="true"
                                data-locale="es-NI"
                                >
                                <thead>
                                  <th data-sortable="true" data-field="id">Id</th>        
                                  <th data-sortable="true" data-field="codigo">Código</th>
                                  <th data-sortable="true" data-field="codigo_barra">Barra</th>
                                  <th data-field="descripcion">Descripción</th>
                                  <th data-field="existencia">Existencia</th>
                                  <th data-field="precio">Precio</th>
                                  <th class="all">Acciones</th>
                                </thead>
                                <tbody>
                                  {% for item in productos %}
                                  <tr>
                                    <td>{{ item.id }}</td>
                                    <td>{{ item.codigo }}</td>
                                    <td>{{ item.codigo_barra }}</td>
                                    <td>{{item.descripcion}}</td>
                                    <td>{{item.existencia}}</td>
                                    <td>{{item.precio}}</td>
                                    <td>
                                        {% if item.existencia > 0 and item.estado %}
                                        <button class="btn btn-warning btn-circle" id="btnSelect" 
                                        onclick="seleccionarProducto({{item.id}},'{{item.codigo}}','{{item.descripcion}}',{{item.precio}})">
                                            <i class="far fa-hand-pointer"></i>
                                        </button>
                                        {% endif %}
                                    </td>
                                  </tr>
                                  {% endfor %}
                                </tbody>
                              </table>
                        </div>
                        <div class="dropdown-divider"></div>
                        <div class="row">
                            <div class="col">
                                <!-- <button type="submit" class="btn btn-danger"><span class="fa fa-save"></span> Guardar</button> -->
                                <button type="button" id="btnCancelar" class="btn btn-success">
                                        <!-- onclick="return cerrar_modal()" -->
                                        Cancelar
                                </button>
                            </div>
                        </div>
                    </div>
                    
                    
                </div>
            </div>
        </div>
    </div>
</div> 
{% block js_page %}
<script>
    $(function () {

        $("#btnCancelar").click(function(e){
            e.preventDefault();
            cerrar_modal();

        });
    });
    $('#tblProducto').bootstrapTable();

    function seleccionarProducto(id,codigo,descripcion,precio){
        $("#codigo").val(codigo);
        $("#descripcion").val(descripcion);
        $("#precio").val(precio);
        $("#btnCancelar").click();
        $("#codigo").select();
        $("#codigo").focus();

    }

</script>
{% endblock %}

facturacion/templates/facturacion/cliente_formulario.html
<div class="modal-dialog modal-lg">
    <div class="modal-content">
        {% if cliente %}
        <form method="POST" role="form" class="form-inline" action="{% url 'facturacion:cliente_editar' cliente.id %}" enctype="multipart/form-data" >
        {% else %}
        <form method="POST" role="form" class="form-inline" action="{% url 'facturacion:cliente_agregar' %}"  enctype="multipart/form-data" >
        {% endif %}
            <div class="col-md-12">
                {% if cliente %}
                <div class="card border-left-warning shadow h-100 py-2">
                {% else %}
                <div class="card border-left-success shadow h-100 py-2">
                {% endif %}
                <div class="card-body">                   
                    <div class="col-12">
                        <div class="text-xs font-weight-bold text-primary text-uppercase mb-1">
                          <h6>  {% if cliente %} Editar {% else %} Nuevo {% endif %} Cliente </h6>
                        </div>
                        <div class="dropdown-divider"></div>
                        {% csrf_token %}
                        <div class="row">
                            <div class="column-6">
                                <div class="input-group">{{form.nombres.label}}</div>
                                <div class="input-group">{{form.nombres}}</div>
                            </div>
                            <div class="column-6">
                                <div class="input-group">{{form.apellidos.label}}</div>
                                <div class="input-group">{{form.apellidos}}</div>
                            </div> 
                        </div>
                        <div class="row">
                            <div class="column-6">
                                <div class="input-group">{{form.tipo.label}}</div>
                                <div class="input-group">{{form.tipo}}</div>
                            </div>
                            <div class="column-6">
                                <div class="input-group">{{form.celular.label}}</div>
                                <div class="input-group">{{form.celular}}</div>
                            </div> 
                        </div>
                          <div class="row">
                            <div class="column-6">
                                <div class="input-group">{{form.estado.label}}</div>
                                <div class="input-group">{{form.estado}}</div>
                            </div>
                            
                        </div>
                        <hr/>
                        <div class="dropdown-divider"></div>
                        <div class="row">
                            <div class="col">
                                <button type="submit" class="btn btn-danger"><span class="fa fa-save"></span> Guardar</button>
                                <button type="button" class="btn btn-success" onclick="return cerrar_modal()">
                                    Cancelar
                                </button>
                            </div>
                        </div>
                    </div>               
                </div>
                </div>
            </div>
        </form>
    </div>
</div>

facturacion/templates/facturacion/clientes.html
{% extends 'app/base.html' %}

{% block contenido %}
<div class="card shadow mb-4">
 <div class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
   <h6 class="m-0 font-weight-bold text-primary">Listado de Productos</h6>
 </div>
 
 <div class="card-body">
  <div class="buttons-toolbar">
    <button
     class="btn btn-success" 
     onclick="return abrir_modal('{% url 'facturacion:cliente_agregar' %}')" >
      <i cass="far fa-calendar-plus"></i> Nuevo
    </a>
  </div>
   <table 
      id="table" 
      data-toggle="table"
      data-pagination="true"
      data-search="true"
      data-show-columns="true"
      data-show-toggle="true"
      data-show-fullscreen="true"
      data-toolbar=".buttons-toolbar"
      data-locale="es-NI"
   >
     <thead>       
      <th data-sortable="true" data-field="nombres">Nombres</th>
      <th data-sortable="true" data-field="apellidos">Apellidos</th>
      <th data-sortable="true" data-field="tipo">Tipo</th>
      <th data-field="telefono">Teléfono</th>
      <th data-field="estado">Estado</th>
      <th class="all">Acciones</th>  
     </thead>
     <tbody>
       {% for item in clientes %}
       <tr>
          <td>{{ item.nombres }}</td>
          <td>{{ item.apellidos }}</td>
          <td>{{item.tipo}}</td>
          <td>{{ item.celular }}</td>
          <td>
            <div onclick="inactivar({{item.id}})">
              {% if item.estado %}
              <i class="far fa-thumbs-up text-primary"></i>
            {% else %}
              <i class="far fa-thumbs-down text-danger"></i>
            {% endif %}
          </div>
          </td>
         <td>
           <button class="btn btn-warning btn-circle" onclick="return abrir_modal('{% url 'facturacion:cliente_editar' item.id %}')" >
             <i class="far fa-edit"></i></button>
         </td>
       </tr>
       {% endfor %}
     </tbody>
   </table>
 </div>
</div>
{% endblock contenido %}

{% block js %}
 <script>
  function inactivar(id)
  {
    var data = {id:id};
    data = JSON.stringify(data);
    var token = '{{csrf_token}}';
    $.ajax({
      headers : {"X-CSRFToken": token},
      type:"POST",
      url:"/facturacion/cliente/estado/"+id,
      data: data,
      success: function(response){
        if(response==="OK")
        {
          location.reload(true);
        }
        else{
           GestionarMensaje.MensajeInfo("Aviso","Error Intentado Cambiar Estado a Cliente");
        }
      },
      error: function(jqXHR, textStatus, errorThrow){
         GestionarMensaje.MensajeInfo("Aviso",errorThrow);
        cerrar_modal();
      }
    });
  }

 </script>
{% endblock js %}

facturacion/templates/facturacion/factura_borrar_datalle.html
<label class="text-danger">¿Anular Producto <b>{{factura_detalle.producto.descripcion}}</b> de factura <b>{{factura_detalle.factura.id}}</b>?</label>
<div>
    <div class="form-group">
        <label class="control-label">Usuario</label>
        <input type="text" id="usuario" class="form-control" required>
    </div>
    <div class="form-group">
        <label class="control-label">Contraseña</label>
        <input type="password" id="password" class="form-control" required>
    </div>
</div>

facturacion/templates/facturacion/factura_imprimir_una.html
{% load static %}
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Listado de Compras</title>
    <link rel="stylesheet" href="{% static 'base/css/recibo.css' %}">
    <style type="text/css">
        @page {
             width: 58mm; 
            size: auto;   
            margin: 0mm;
            }
    </style>
</head>
<body onload="window.print()" class="receipt">
    <div class="col-md-1 col-sm-1 col-xs-1 col-xl-1">
        <center>
            <b class="text-center">Tienda </b><br> 
            <small>Direccion</small><br>
            <small>FACTURA No. {{factura_encabezado.factura}}</small><br>
        </center>
        <small>
            <br>
            <b>Factura No.:</b>&nbsp;&nbsp;{{factura_encabezado.id}}&nbsp;&nbsp;
            <b>Fecha Fact:</b>&nbsp;&nbsp;{{factura_encabezado.fecha}}&nbsp;&nbsp; <br>
            <b>Cliente:</b>&nbsp;&nbsp;{{factura_encabezado.cliente.id}}&nbsp;&nbsp;- {{factura_encabezado.cliente}}<br>
            <br><br>
        </small>
        <table class="table table-condensed table-sm" width="60%">
            <thead>
                <th>Código</th>
                <th  align='right'>Cant.</th>
                <th  align='right'>P. Unit.</th>
                <th  align='right'>Sub Total</th>
                <th  align='right'>Descuento</th>
                <th  align='right'>Total</th>
            </thead>
            <tbody>
                {% for item in factura_detalle %}
                <tr>
                    <td>{{item.producto.id}}</td>
                    <td>{{item.cantidad}}</td>
                    <td>{{item.precio}}</td>
                    <td>{{item.sub_total}}</td>
                    <td>{{item.descuento}}</td>
                    <td>{{item.total}}</td>
                </tr>
                <tr>
                    <td colspan="5">{{item.producto}}</td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
        <div class="col-xs-1"></div>
        <div class="col-xs-11">
            <div class="pull-right">
            <table class="table-responsive dt-responsive nowrap">
                <thead>
                    <th colspan=2>Totales</th>
                </thead>
                <tbody>
                    <tr>
                        <td>Sub Total:</td> <td align='right'>{{factura_encabezado.sub_total}}</td>
                    </tr>
                    <tr>
                        <td>Iva:</td> <td align='right'>{{factura_encabezado.descuento}}</td>
                    </tr>
                    <tr>
                        <td>Total:</td> <td align='right'><b>{{factura_encabezado.total}}</b></td>
                    </tr>
                </tbody>
            </table>
            </div>
        </div>
        <div class="row">
        <small class="pie">
            <br><br>
            <center>
                Creada por:  {{factura_encabezado.usuario_creador}} - Fecha:  {{factura_encabezado.fecha_creacion}}
                <br>
                <i>&copy; &reg; <b>Andy Miguel Ryes</b><br> - andymrrrr@gmail.com</i> 
            </center>
        </small>
        </div>
    </div>
</body>
</html>

facturacion/templates/facturacion/facturas_listado.html
{% extends 'app/base.html' %} {% block contenido %}
<div class="card shadow mb-4">
  <div
    class="card-header py-3 d-flex flex-row align-items-center justify-content-between"
  >
    <h6 class="m-0 font-weight-bold text-primary">Listado de Facturas</h6>
  </div>
  <!-- Card Body -->
  <div class="card-body">
    <div class="row">
      <div class="col-md-4">
        <input
          type="text"
          class="form-class fecha"
          name="fechainicio"
          id="fechainicio"
          readonly
        />
      </div>
      <div class="col-md-4">
        <input
          type="text"
          class="form-class fecha"
          name="fechafinal"
          id="fechafinal"
          readonly
        />
      </div>
      <div class="col-md-4">
        <button class="btn btn-warning" type="button" id="btnPrint">
          Imprimir
        </button>
      </div>
    </div>
    <hr />
    <div class="buttons-toolbar">
      <a class="btn btn-success" href="{% url 'facturacion:facturas_agregar' %}"
        ><i cass="far fa-calendar-plus"></i> Nuevo</a
      >
    </div>

    <table
      id="table"
      data-toggle="table"
      data-pagination="true"
      data-search="true"
      data-show-columns="true"
      data-show-toggle="true"
      data-show-fullscreen="true"
      data-toolbar=".buttons-toolbar"
      data-locale="es-NI"
    >
      <thead>
        <th data-sortable="true" data-field="id">No.</th>
        <th data-sortable="true" data-field="nombres">Cliente</th>
        <th data-sortable="true" data-field="apellidos">Total</th>
        <th data-field="estado">Estado</th>
        <th class="all">Acciones</th>
      </thead>
      <tbody>
        {% for item in facturas%}
        <tr>
          <td>{{ item.id }}</td>
          <td>{{ item.cliente }}</td>
          <td>{{ item.total }}</td>
          <td>{{item.estado|yesno:"Activo,Inactivo"}}</td>
          <td>
            <a
              href="{% url 'facturacion:factura_editar' item.id %}"
              class="href btn btn-warning btn-circle"
            >
              <i class="far fa-edit"></i>
            </a>
          </td>
        </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
  {% endblock contenido %} {% block js %}
  <script>
    $(function () {
      $(".fecha").datetimepicker({
        format: "Y-m-d",
        timepicker: false,
      });

      $("#btnPrint").click(function (e) {
        e.preventDefault();
        var fechainicio,
          fechafinal,
          hoy = new Date();
        fechainicio = $("#fechainicio").val();
        fechafinal = $("#fechafinal").val();
        if (fechainicio == "" || fechainicio == null) {
          fechainicio =
            hoy.getFullYear() + "-" + hoy.getMonth() + "-" + hoy.getDate();
        }
        if (fechafinal == "" || fechafinal == null) {
          var fechafinal =
            hoy.getFullYear() +
            "-" +
            (hoy.getMonth() + 1) +
            "-" +
            hoy.getDate();
        }

        var url = "imprimir-todas/" + fechainicio + "/" + fechafinal;

        window.open(url, "facturas");
      });
    });
  </script>
  {% endblock %}
</div>